export const lessons = [
  'Subject and Verb Agreement',
  'Verb Tenses',
  'if conditionals',
  'Pronouns',
  'Pronoun Usage',
  'Comparison and Superlative',
  'Parallel Structure',
  'Modifiers',
  'Transition Words',
  'Punctuation Marks',
  'Rhetorical Synthesis',
  'Main Ideas',
  'Making Inferences',
  'Command of Evidence',
  'Command of Evidence- Support',
  'Command of Evidence- Weaken',
  'Command of Evidence- Graphs',
  'Cross-Text Connections',
  'Text, Structure, and Purpose',
  'Words in Context',
  'Words in Context- Gap Filling ',
  'Words in Context- Synonyms',
  'Supporting Evidence and Examples',
  'Topic, Conclusion, and Transition Sentences',
  'Sentence Placement',
  'Relevance and Purpose',
  'Boundaries',
  'Form, Structure, and Sense',
  'Details Question',
  'Main Purpose',
  'Overall Structure',
  'Underlined Purpose',
  'DSAT Exam 1',
  'DSAT Exam 2',
  'DSAT Exam 3',
  'DSAT Exam 4',
  'DSAT Exam 5',
  'DSAT Exam 6',
  'DSAT Exam 7',
  'DSAT Exam 8',
  'DSAT Exam 9',
  'DSAT Exam 10',
];